version: "3.9"

services:
  backend:
    build:
      image: ghcr.io/nsirmariem/task-manager-backend:latest
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      JWT_SECRET: dev-jwt-secret
    restart: unless-stopped

  frontend:
    build:
      image: ghcr.io/nsirmariem/task-manager-frontend:latest
      dockerfile: Dockerfile
    ports:
      - "4173:80"
    environment:
      VITE_API_BASE_URL: http://backend:8081/api
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: task-manager-network
